### ISSUE TITLE
TFExplorer: workload is still alive after the pool has been expired

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfexplorer#274]
**Pool:** https://explorer.devnet.grid.tf/api/v1/reservations/pools/3237
**workloads:**
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/17941
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/17925

**Comment by muhamadazmy** [comment]
@AhmedHanafy725 explorer was updated for some other fix, and unfortunately restarting the explorer always force syncing of the pool so this pool state has been fixed. 

We will keep this issue open until it happens again, mean while i am still reviewing the code

**Comment by muhamadazmy** [comment]
@AhmedHanafy725 this issue has been fixed in this PR #278 the idea is that we have a max delay for expired pools checks of an hour, so even a pool was somehow skipped, it will be worst case of an hour before it's checked again.

**Comment by AhmedHanafy725** [comment]
this happens again, the pool expired 2 hours ago and still have active workloads.
pools: https://explorer.devnet.grid.tf/api/v1/reservations/pools/5635
workloads:
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/25247
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/25259
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/25235

**Comment by weynandkuijpers** [comment]
This issue has not been update for a long time.  Please reconsider if this is part if this release or the next.  I'll remove it if not update and considered part of this release.

**Comment by LeeSmet** [comment]
All workloads still live on the pool seem to be networks. This is intended (i.e. they don't get cleaned up on pool expiration because they don't use any (currently tracked) resources). As for the listed workloads, those got deleted the 4th of feb, same day as the issue was posted. It is possible that there is some delay before a workload is _actually_ deleted on a node, and it will only be removed from the pool when the node sends a confirmation to the explorer that is has been deleted. Deleting is done by the provision engine. This means that if the engine is stuck, the workload will not get deleted until such a time where the engine resumes normal operation.

Considering this is devnet, and there have been such occurences in the past (engine stuck because of panic, other bug, ...), I'm going to close the issue (as it resolved itself relatively shortly). Keep in mind that this is devnet, and such things can happen here. If at some point such a situation happens again, feel free to open a new issue.
